const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

const MEM_DIR = 'memories';
const CHUNK_DIR = 'memories/chunks';
const THUMB_DIR = 'memories/thumbs';
const DB_PATH = 'memories/database.json';
const CHUNK_SIZE = 300;

if (!fs.existsSync(CHUNK_DIR)) fs.mkdirSync(CHUNK_DIR, { recursive: true });
if (!fs.existsSync(THUMB_DIR)) fs.mkdirSync(THUMB_DIR, { recursive: true });

// 1. DATABÁZE
let existingDb = [];
try {
    if (fs.existsSync(DB_PATH)) existingDb = JSON.parse(fs.readFileSync(DB_PATH, 'utf8'));
} catch (e) { }

const diskFiles = fs.readdirSync(MEM_DIR).filter(f => f.startsWith('mem_') && f.endsWith('.webm'));
const existingMap = new Set(existingDb.map(m => m.filename));
const diskMap = new Set(diskFiles);

let db = existingDb.map(m => {
    if (!diskMap.has(m.filename)) m.deleted = true;
    return m;
});

const newFiles = diskFiles.filter(f => !existingMap.has(f));
const newEntries = newFiles.map(f => ({
    filename: f,
    timestamp: parseInt(f.split('_')[1]) || Date.now(),
    stats: { volume: 50, color: '#888888', motion: 50, brightness: 50 }
}));

if (newEntries.length > 0) {
    db = db.concat(newEntries.sort((a, b) => a.timestamp - b.timestamp));
}

fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2));

// 2. NÁHLEDY (Generuje se každý 5. snímek)
console.log("Generuji náhledy...");
db.forEach((mem, index) => {
    if (index % 5 === 0) {
        const thumbPath = path.join(THUMB_DIR, `thumb_${index}.jpg`);
        const vidPath = path.join(MEM_DIR, mem.filename);
        if (!fs.existsSync(thumbPath)) {
            try {
                // Rychlý náhled (scale 160px na šířku)
                if (mem.deleted) {
                    execSync(`ffmpeg -f lavfi -i color=c=black:s=160x120 -vframes 1 -q:v 10 "${thumbPath}" -y`, { stdio: 'ignore' });
                } else {
                    execSync(`ffmpeg -ss 0.0 -i "${vidPath}" -vframes 1 -vf scale=160:-1 -q:v 10 "${thumbPath}" -y`, { stdio: 'ignore' });
                }
            } catch (e) { }
        }
    }
});

// 3. CHUNKY (VP9 + AUDIO)
const totalChunks = Math.ceil(db.length / CHUNK_SIZE);
for (let i = 0; i < totalChunks; i++) {
    const chunkName = `chunk_${i}.webm`;
    const chunkPath = path.join(CHUNK_DIR, chunkName);

    if (!fs.existsSync(chunkPath)) {
        console.log(`Generuji ${chunkName}...`);
        const slice = db.slice(i * CHUNK_SIZE, (i + 1) * CHUNK_SIZE);
        const tempDir = `temp_img_${i}`;

        if (fs.existsSync(tempDir)) fs.rmSync(tempDir, { recursive: true, force: true });
        fs.mkdirSync(tempDir);

        try {
            let count = 0;
            slice.forEach((mem, idx) => {
                const vPath = path.join(MEM_DIR, mem.filename);
                const iPath = path.join(tempDir, `img_${String(idx).padStart(4, '0')}.jpg`);
                try {
                    if (mem.deleted) {
                        execSync(`ffmpeg -f lavfi -i color=c=black:s=640x480 -vframes 1 -q:v 2 "${iPath}" -y`, { stdio: 'ignore' });
                    } else {
                        execSync(`ffmpeg -ss 0.0 -i "${vPath}" -vframes 1 -q:v 2 "${iPath}" -y`, { stdio: 'ignore' });
                    }
                    count++;
                } catch (e) { }
            });

            if (count > 0) {
                // VP9 + OPUS AUDIO (Tichá stopa generated by lavfi, aby prohlížeč nepanikařil)
                // Nebo pokud chceš původní audio, je to složitější u fotek.
                // Zde generujeme "němou" audio stopu, aby video mělo audio track a neblblo.
                execSync(`ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -framerate 30 -i ${tempDir}/img_%04d.jpg -c:v libvpx-vp9 -b:v 2000k -c:a libopus -shortest -vf "setpts=N/30/TB,format=yuv420p" -g 30 -row-mt 1 "${chunkPath}"`);
                console.log("Chunk hotov.");
            }
        } catch (e) { console.error(e.message); }
        try { fs.rmSync(tempDir, { recursive: true, force: true }); } catch (e) { }
    }
}
